// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnPAjckHTbHTqAa7Fkh3SRtuqXuFkJ4vM',
    appId: '1:139914337046:web:6aea70da4a629b97294e37',
    messagingSenderId: '139914337046',
    projectId: 'capstone-672aa',
    authDomain: 'capstone-672aa.firebaseapp.com',
    storageBucket: 'capstone-672aa.firebasestorage.app',
    measurementId: 'G-8HQ0F8B6KY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvg-AOK_UaGj4mLDwyLIxDNgy8t-UzEp8',
    appId: '1:139914337046:android:b5ddfa2372ad7450294e37',
    messagingSenderId: '139914337046',
    projectId: 'capstone-672aa',
    storageBucket: 'capstone-672aa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhqDI2kpmhnFar3kqSFwAOXjrnR89Sqks',
    appId: '1:139914337046:ios:2655015d2b36107e294e37',
    messagingSenderId: '139914337046',
    projectId: 'capstone-672aa',
    storageBucket: 'capstone-672aa.firebasestorage.app',
    iosBundleId: 'com.example.layoutX1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhqDI2kpmhnFar3kqSFwAOXjrnR89Sqks',
    appId: '1:139914337046:ios:2655015d2b36107e294e37',
    messagingSenderId: '139914337046',
    projectId: 'capstone-672aa',
    storageBucket: 'capstone-672aa.firebasestorage.app',
    iosBundleId: 'com.example.layoutX1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAnPAjckHTbHTqAa7Fkh3SRtuqXuFkJ4vM',
    appId: '1:139914337046:web:984b068e44216e36294e37',
    messagingSenderId: '139914337046',
    projectId: 'capstone-672aa',
    authDomain: 'capstone-672aa.firebaseapp.com',
    storageBucket: 'capstone-672aa.firebasestorage.app',
    measurementId: 'G-3SWXGJYEX1',
  );

}